# TXT File Plotter
Goal: Plot a SeapHOx text file

In [5]:
import numpy as np
import pandas as pd
# import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import os
import pytz

%matplotlib widget

### Scrape Google Sheets
Use datasheets library, following directions from https://datasheets.readthedocs.io/en/latest/index.html

In [6]:
df = pd.read_csv('Data/ahl_0417.txt', header = 23, delimiter='\t', parse_dates=[1])
df.set_index('Sample Time', inplace=True)
df.head()

,Sample #,Main Batt,Vtherm,Vint,Vext Ref,Iso Batt,Controller Temp,pH Temp,Pressure (dBar),pH Int,...,Substrate Leak,P/N,S/N,Oxygen uM,O2 Sat,Optode Temp,SBE Temp,Conductivity,Salinity,Unnamed: 22
Sample Time,,,,,,,,,,,,,,,,,,,,,
2018-04-17 17:44:09,#0000000,18.86,1.02812,0.065281,-0.844298,5.77,24.74,23.723,-0.431,7.741560,...,0.4573,4835,496,270.665,101.601,23.274,19.6927,0.00011,0.0098,NaN
2018-04-17 18:00:25,#0000001,18.87,0.95605,0.065410,-0.843284,5.75,24.23,26.072,-0.422,7.726531,...,0.4506,4835,496,266.282,105.301,26.080,21.1743,0.00012,0.0104,NaN
2018-04-17 18:30:25,#0000002,18.86,1.29097,0.079854,-0.833078,5.76,19.75,16.071,5.336,8.053491,...,0.7175,4835,496,328.516,102.900,14.374,13.4374,3.98594,33.5586,NaN
2018-04-17 19:00:25,#0000003,18.87,1.35269,0.080552,-0.833311,5.75,16.48,14.427,5.416,8.080040,...,1.0302,4835,496,328.323,101.557,13.802,13.4879,3.99098,33.5614,NaN
2018-04-17 19:30:25,#0000004,18.86,1.37305,0.080018,-0.833261,5.75,15.65,13.894,5.388,8.075366,...,1.0911,4835,496,325.823,100.482,13.667,13.5380,3.99540,33.5589,NaN

### Filter
- Filter based on date
- Cast to type float (for some reason the str.split leaves it as arbitrary object)
- This was necessary in early notebook as the input data wasn't filtered at all but the Google Sheet should be cleaner to begin with (*i.e.*, no land data)
- Filtration may come in handy later so keep this here for now

In [7]:
date_filt = df.index > '2018-04-17 18:30:00'
df_filt = df[date_filt]


pacific = pytz.timezone('US/Pacific')
df_filt.index = df_filt.index.tz_localize(pytz.utc).tz_convert(pacific)
df_filt.head()

,Sample #,Main Batt,Vtherm,Vint,Vext Ref,Iso Batt,Controller Temp,pH Temp,Pressure (dBar),pH Int,...,Substrate Leak,P/N,S/N,Oxygen uM,O2 Sat,Optode Temp,SBE Temp,Conductivity,Salinity,Unnamed: 22
Sample Time,,,,,,,,,,,,,,,,,,,,,
2018-04-17 11:30:25-07:00,#0000002,18.86,1.29097,0.079854,-0.833078,5.76,19.75,16.071,5.336,8.053491,...,0.7175,4835,496,328.516,102.900,14.374,13.4374,3.98594,33.5586,NaN
2018-04-17 12:00:25-07:00,#0000003,18.87,1.35269,0.080552,-0.833311,5.75,16.48,14.427,5.416,8.080040,...,1.0302,4835,496,328.323,101.557,13.802,13.4879,3.99098,33.5614,NaN
2018-04-17 12:30:25-07:00,#0000004,18.86,1.37305,0.080018,-0.833261,5.75,15.65,13.894,5.388,8.075366,...,1.0911,4835,496,325.823,100.482,13.667,13.5380,3.99540,33.5589,NaN
2018-04-17 13:02:20-07:00,#0000005,18.86,1.38109,0.079462,-0.833338,5.75,15.71,13.685,5.354,8.067436,...,1.1070,4835,496,324.289,99.912,13.623,13.5492,3.99679,33.5621,NaN
2018-04-17 13:32:51-07:00,#0000006,18.85,1.38211,0.079592,-0.832930,5.73,15.34,13.658,5.219,8.069951,...,1.1183,4835,496,326.275,100.658,13.683,13.6530,4.00669,33.5635,NaN

### Plot

In [14]:
fig, axs = plt.subplots(7, 1, figsize = (10, 10), sharex = True)
axs[0].plot(df_filt.index, df_filt.loc[:, 'Main Batt'])
axs[0].set_ylabel('V_batt')

axs[1].plot(df_filt.index, df_filt.loc[:, 'Pressure (dBar)'], 'k')
axs[1].set_ylabel('P (dbar)')

axs[2].plot(df_filt.index, df_filt.loc[:, 'Salinity'], 'k')
axs[2].set_ylabel('Salinity')
axs[2].set_ylim([33.3, 34.3])

axs[3].plot(df_filt.index, df_filt.loc[:, 'SBE Temp'], 'k')
axs[3].set_ylabel('Temp (C)')

axs[4].plot(df_filt.index, df_filt.loc[:, 'Vint'], 'k')
axs[4].set_ylabel('V_int')
ax2 = axs[4].twinx()
ax2.plot(df_filt.index, df_filt.loc[:, 'Vext Ref'], 'b')
ax2.set_ylabel('V_ext', color='b')
ax2.tick_params('y', colors='b')

axs[5].plot(df_filt.index, df_filt.loc[:, 'pH Int'], 'k', label = 'pH Int')
axs[5].plot(df_filt.index, df_filt.loc[:, 'pH Ext'], 'b', label = 'pH Int')
axs[5].legend(loc='upper left')
axs[5].set_ylabel('pH')

axs[6].plot(df_filt.index, df_filt.loc[:, 'Oxygen uM'], 'k')
axs[6].set_ylabel('O2 (uM)')

axs[0].xaxis_date() # make sure it knows that x is a date/time

for axi in axs.flat:
#     axi.xaxis.set_major_locator(plt.MaxNLocator(3))
#     print(axi)
    axi.yaxis.set_major_locator(plt.MaxNLocator(3))
#     axi.yaxis.set_major_formatter(ticker.FormatStrFormatter("%.02f"))

fig.autofmt_xdate() # makes the date labels easier to read.
plt.tight_layout()
plt.savefig('test_dep_01.png')

FigureCanvasNbAgg()